# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone X",
  "iPad Pro (12.9-inch)",
  "iPad Pro (9.7-inch)"
])

languages([
  "en-US"
])

# Arguments to pass to the app on launch. See https://github.com/fastlane/snapshot#launch_arguments
#launch_arguments("-username Felix")

# The name of the scheme which contains the UI Tests
scheme "core-x"

OTHER_SWIFT_FLAGS='$(inherited) -D SNAPSHOT'

reinstall_app true

clear_previous_screenshots # remove the '#' to clear all previously generated screenshots before creating new ones

stop_after_first_error true

# For more information about all available options run
# snapshot --help
